server:
  host: localhost
  port: 8081

# spring:
#   datasource:
#     url: jdbc:h2:mem:mydb
#     username: sa
#     password: password
    # driverClassName: org.h2.Driver
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mysql
    username: <login>
    password: <password>
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
   hikari:
     connection-timeout: 60000
     maximum-pool-size: 10
